config/routes.rb
Rails.application.routes.draw do
 
resources :reviews do
	resources :comments
		end

root "reviews#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review

validates :body, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

# add an association that has a 1-to-many relationship
has_many :comments

geocoded_by :address
after_validation :geocode

validates :title, presence: true
validates :body, length: { minimum: 10 }
validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }
validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
validates :restaurant, presence: true
validates :address, presence: true

def to_param
id.to_s + "-" + title.parameterize
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
@review = Review.find(params[:review_id])

@comment = @review.comments.new(params.require(:comment).permit(:body))

@comment.save 

# go back to the review show page
redirect_to review_path(@review)
end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def index
# this is our list page for our reviews

@price = params[:price]
@cuisine = params[:cuisine]
@location = params[:location]

# start with all the reviews
@reviews = Review.all


# filtering by price
if @price.present?
	@reviews = @reviews.where(price: @price)
	end

# filter by cuisine
if @cuisine.present?
	@reviews = @reviews.where(cuisine: @cuisine)
	end

# search near the location
if @location.present?
	@reviews = @reviews.near(@location)
	end

end

def new
	# the form for adding a new review
@review = Review.new
end

def create
# take info from the form and add it to the model
@review = Review.new(form_params)

# we want to check if the model can be saved

# if it is, we're going to the home page again

# if it isn't show the new form
if @review.save
	redirect_to root_path
else 
	# show the view for new.html.erb
	render "new"
	end

end


def show
# individual review page
@review = Review.find(params[:id])
end


def destroy
# find the individual review
@review = Review.find(params[:id])

# destroy
@review.destroy

# redirect to the home page
redirect_to root_path
	end


def edit
# find the individual review (to edit)
@review = Review.find(params[:id])
end

def update
# find the individual review
@review = Review.find(params[:id])

# update with the new info from the form
if @review.update(form_params)

# redirect somewhere new
redirect_to review_path(@review)
else render "edit"
end

end


def form_params
params.require(:review).permit(:title, :restaurant, :price, :body, :cuisine, :score, :ambiance, :address)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_price(price)
  if price == 1
    "$"
  elsif price == 2
    "$$"
  elsif price == 3
    "$$$"
  end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews - the best restaurants in the world</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <nav>
  <h1>
    <%=link_to root_path do %>
      <%= image_tag "bien-logo.svg" %>
      <% end %>
    </h1>
  </nav>
<nav>
<%= link_to "Add a review", new_review_path %>
</nav>
</header>

<main>
    <%= yield %>
</main>

    <footer>
Copyright 2018 Bien Reviews
</footer>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
<%= f.input :title %>
<%= f.input :restaurant %>
<%= f.input :address %>
<%= f.input :body %>
<%= f.input :cuisine %>
<%= f.input :price %>
<%= f.input :score %>
<%= f.input :ambiance %>

<%= f.button :submit %>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit your new restaurant reviews!</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<nav class="filters">
	<%= active_link_to "All restaurants", root_path, active: { price: nil, cuisine: nil, location: nil } %>
	<div>
	<%= active_link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location), active: { price: 1 }  %>
	<%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location), active: { price: 2 } %>
	<%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location), active: { price: 3 } %>
</div>

<div>
	<%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price, location: @location), active: { cuisine: "Indian" } %>
	<%= active_link_to "Korean", root_path(cuisine: "Korean", price: @price, location: @location), active: { cuisine: "Korean" } %>
	<%= active_link_to "American", root_path(cuisine: "American", price: @price, location: @location), active: { cuisine: "American" } %>
	<%= active_link_to "Japanese", root_path(cuisine: "Japanese", price: @price, location: @location), active: { cuisine: "Japanese" } %>
</div>

<form action"/">
<input type="text" name="location" 
	placeholder="Search location..." value="<%= @location %>">
	<input type="hidden" name="price" value="<%= @price %>">
	<input type="hidden" name="cuisine" value="<%= @cuisine %>">
</form>

</nav>





<% @reviews.each do |review| %>

<div class="review">
	<%= link_to review_path(review) do %>
<h2><%= review.title %></h2>
<p>
	<%= review.cuisine %> -
	<%= pluralize review.comments.count, "comment" %>
		
	</p>
<% end %>
</div>

	<% end %>


app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add your new restaurant reviews!</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>
<% if @review.price.present? %>
<div class="price">
	<%= display_price @review.price %> /$$$
</div>
<% end %>
<div class="score">
	<%= @review.score %> /10
</div>

<% if @review.cuisine.present? %>
	<div class="cuisine">
	Cuisine: <%= @review.cuisine %>
	</div>
<% end %>

<% if @review.ambiance.present? %>
	<div class="ambience">
	Ambience: <%= @review.ambiance %>
	</div>
<% end %>

<div class="body">
<%= simple_format @review.body %>
	</div>

	<div class="actions">
		<%= link_to "Edit this review", edit_review_path(@review) %>
<%= link_to "Delete this review", review_path(@review), method: :delete, data:{confirm: "Are you sure?"} %>
	</div>



	<h3>Comments</h3>
<% @review.comments.order("created_at desc").each do |comment| %>
<div class="comment">
<%= simple_format comment.body %>
<p class="posted">Posted <%= time_ago_in_words comment.created_at %> ago</p>
	</div>
<% end %>


	<h3>Add a comment</h3>

<%= simple_form_for [@review, Comment.new] do |f| %>
	<%= f.input :body %>
	<%= f.button :submit, "Add comment" %>
<% end %>